feat: improve UX for sign up, add data source and first create report
Also fixes some bugs found on the way, adds a standard MutationResult
type, squashes some overly verbose GraphQL error logging (for
forbidden or object does not exist errors).

Adds NEXT_PUBLIC_FRONTEND_BASE_URL required env var to the frontend.

diff --git a/script/import-all-data b/script/import-all-data
--- a/script/import-all-data
+++ b/script/import-all-data
@@ -1,8 +1,5 @@
 #!/bin/bash
 
-# abort on any errors
-set -e
-
 # check that we are in the expected directory
 cd `dirname $0`/..
 
@@ -11,9 +8,25 @@ cd `dirname $0`/..
 
 COMMANDS=$(find hub/management/commands/ -name 'import_*' -printf '%f\n' | sed 's#[.]py##')
 
+REQUIRED_COMMANDS=(
+    "import_last_election_data"
+)
+
 for COMMAND in $COMMANDS
 do
+    # Exit on errors if $COMMAND is in $REQUIRED_COMMANDS (thanks ChatGPT)
+    if [[ "${REQUIRED_COMMANDS[@]}" =~ "$COMMAND" ]]; then
+        set -e
+    fi
+
     if [ "$COMMAND" != "import_areas" ] && [ "$COMMAND" != "import_mps" ]; then
         ./manage.py "$COMMAND"
+
+        if [ $? != 0 ]; then
+            echo "WARN: Ignoring error in script $COMMAND"
+        fi
     fi
+
+    # Reset script to ignore errors if errors were temporarily prevented
+    set +e
 done
